In [58]:
import pandas as pd
import numpy as np
pd.__version__

import pickle

In [2]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# %load executionTimeCheck.py
from time import time, strftime, localtime
from datetime import timedelta


class checkExecution:
    def __init__(self):
        self.startTime = ''

    def secondsToStr(self, elapsed=None):
        if elapsed is None:
            return strftime("%Y-%m-%d %H:%M:%S", localtime())
        else:
            return str(timedelta(seconds=elapsed))

    def log(self, s, elapsed=None):
        line = "=" * 40
        print()
        print(line)
        print(self.secondsToStr(), '-', s)
        if elapsed:
            print("Elapsed time:", elapsed)
        print(line)
        print()

    def startLog(self):
        self.startTime = time()
        self.log("Start Program")

    def endLog(self):
        end = time()
        elapsed = end - self.startTime
        self.log("End Program", self.secondsToStr(elapsed))

In [3]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = ['a', 'b', 'c', 'd'])

In [8]:
print(type(data.a))

<class 'numpy.float64'>


In [12]:
data.index = [2, 3, 4, 6]
data[2]

0.25

In [15]:
population_dict = {'California': 38332521,
                  'Texas': 26448193,
                  'New York': 19651127,
                  'Florida': 19552860,
                  'Illinois': 12882135}

In [16]:
population = pd.Series(population_dict)

In [17]:
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [20]:
population['California': 'Florida']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
dtype: int64

In [21]:
area_dict = {'California': 38332521,
                  'Texas': 26448193,
                  'New York': 19651127,
                  'Florida': 19552860,
                  'Illinois': 12882135}

In [22]:
area = pd.Series(area_dict)

In [23]:
area

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [24]:
states = pd.DataFrame({'population': population, 'area': area})

In [25]:
states

population      area
California    38332521  38332521
Texas         26448193  26448193
New York      19651127  19651127
Florida       19552860  19552860
Illinois      12882135  12882135

In [27]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [28]:
states.columns

Index(['population', 'area'], dtype='object')

In [29]:
states.area

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: area, dtype: int64

In [30]:
data = [{'a': i, 'b': i*2} for i in range(3)]

In [31]:
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [32]:
pd.DataFrame(np.random.rand(3, 2), columns=['foo', 'bar'], index=['a', 'b', 'c'])

foo       bar
a  0.516722  0.506109
b  0.736876  0.015004
c  0.673605  0.948983

In [33]:
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [34]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

In [36]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [37]:
ind[1]

3

In [38]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [39]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


In [40]:
ind[1] = 0

TypeError: Index does not support mutable operations

In [41]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])
indA & indB 

Int64Index([3, 5, 7], dtype='int64')

In [42]:
indA | indB

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [43]:
indA ^ indB

Int64Index([1, 2, 9, 11], dtype='int64')

In [44]:
indA.intersection(indB)

Int64Index([3, 5, 7], dtype='int64')

In [45]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])

In [46]:
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [47]:
'a' in data

True

In [48]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [49]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [50]:
data['e'] = 1.25

In [51]:
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [52]:
data['a'] = 0

In [53]:
data

a    0.00
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [54]:
data['a': 'c']

a    0.00
b    0.50
c    0.75
dtype: float64

In [57]:
data[ (data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [113]:
data = pd.Series(['e','a', 'b','f', 'a','c', 'd'], index=[0,1, 4,2.2,  3, 5, 6])
data

0.0    e
1.0    a
4.0    b
2.2    f
3.0    a
5.0    c
6.0    d
dtype: object

In [114]:
data[1]

'a'

In [118]:
data.loc[1:3]

1.0    a
4.0    b
2.2    f
3.0    a
dtype: object

In [119]:
data.iloc[1]

'a'

In [120]:
data.iloc[1:3]

1.0    a
4.0    b
dtype: object

In [60]:
with open('/Users/tax_k/Projects/AI-DL/KB/Dataset/final_total_data.txt', 'rb') as f:
    whole_data = pickle.load(f)

In [130]:
whole_data.columns.values

array(['deal_price', 'deal_year', 'deal_month', 'loc_code_x', 'dong',
       'area', 'current_floor', 'total_unit', 'total_building',
       'max_floor', 'min_floor', 'total_parking', 'unit_parking',
       'conv_lists', 'medi_lists', 'park_lists', 'road_lists',
       'kindergarten', 'elementary_school', 'middle_school',
       'high_school', 'university', 'etc_lists', 'S-Line1', 'S-Line2',
       'S-Line3', 'S-Line4', 'S-Line5', 'S-Line6', 'S-Line7', 'S-Line8',
       'S-Line9', 'S-LineBD', 'S-LineNBD', 'S-LineGC', 'S-LineJA',
       'S-LineAir', 'distance', 'cont_rank', 'com_year', 'com_mon',
       'avg_price', 'sub_num', 'bldg_age', 'lv_fg'], dtype=object)

In [95]:
top_ranker = whole_data[(whole_data.cont_rank < 100)]

In [96]:
len(top_ranker)

1966

In [97]:
top_ranker["avg_price"].mean()

593.3855544252289

In [70]:
lower_ranker = whole_data[(whole_data.cont_rank >= 100)]

In [71]:
len(lower_ranker)

971818

In [72]:
lower_ranker["avg_price"].mean()

601.5260244202103

In [148]:
area = pd.Series({'California': 423967, 'Texas': 695662, 'New York':141297, 'Florida': 170312, 'Illinois': 149995})
pop = pd.Series({'California': 38123100, 'Texas': 12312002, 'New York':1986900, 'Florida': 19750084, 'Illinois': 128888})
data = pd.DataFrame({'area':area, 'pop': pop})

In [149]:
data

area       pop
California  423967  38123100
Texas       695662  12312002
New York    141297   1986900
Florida     170312  19750084
Illinois    149995    128888

In [150]:
data.area is data['area']

True

In [151]:
data.pop is data['pop']

False

In [152]:
data['density'] = data['pop'] / data['area']

In [153]:
data

area       pop     density
California  423967  38123100   89.919970
Texas       695662  12312002   17.698253
New York    141297   1986900   14.061870
Florida     170312  19750084  115.964136
Illinois    149995    128888    0.859282

In [154]:
data.values

array([[4.23967000e+05, 3.81231000e+07, 8.99199702e+01],
       [6.95662000e+05, 1.23120020e+07, 1.76982529e+01],
       [1.41297000e+05, 1.98690000e+06, 1.40618697e+01],
       [1.70312000e+05, 1.97500840e+07, 1.15964136e+02],
       [1.49995000e+05, 1.28888000e+05, 8.59281976e-01]])

In [155]:
data.T

California         Texas      New York       Florida       Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  149995.000000
pop      3.812310e+07  1.231200e+07  1.986900e+06  1.975008e+07  128888.000000
density  8.991997e+01  1.769825e+01  1.406187e+01  1.159641e+02       0.859282

In [156]:
data.values[0]

array([4.23967000e+05, 3.81231000e+07, 8.99199702e+01])

In [157]:
data.iloc[:3, :2]

area       pop
California  423967  38123100
Texas       695662  12312002
New York    141297   1986900

In [158]:
data.loc[:'Illinois', :'pop']

area       pop
California  423967  38123100
Texas       695662  12312002
New York    141297   1986900
Florida     170312  19750084
Illinois    149995    128888

In [159]:
data.ix[:3, :'pop']

/Users/tax_k/anaconda3/envs/DL/lib/python3.6/site-packages/ipykernel/__main__.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  if __name__ == '__main__':


area       pop
California  423967  38123100
Texas       695662  12312002
New York    141297   1986900

In [162]:
data.loc[(data.density < 100) & (data.density > 10), ['pop', 'density']]

pop    density
California  38123100  89.919970
Texas       12312002  17.698253
New York     1986900  14.061870

In [163]:
data.iloc[0, 1] = 90

In [164]:
data['Florida': 'Illinois']

area       pop     density
Florida   170312  19750084  115.964136
Illinois  149995    128888    0.859282

In [165]:
data[1:3]

area       pop    density
Texas     695662  12312002  17.698253
New York  141297   1986900  14.061870

In [166]:
data[data.density > 100]

area       pop     density
Florida  170312  19750084  115.964136

In [169]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int64

In [171]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)), columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  1  7  5  1
1  4  0  9  5
2  8  0  9  2

In [172]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [173]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [174]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [175]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)), columns=list('AB'))
A

A   B
0  11  19
1   2   4

In [177]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)), columns=list('BAC'))
B

B  A  C
0  9  8  9
1  4  1  3
2  6  7  2

In [178]:
A + B

A     B   C
0  19.0  28.0 NaN
1   3.0   8.0 NaN
2   NaN   NaN NaN

In [180]:
fill = A.stack().mean()
fill

9.0

In [181]:
A.add(B, fill_value=fill)

A     B     C
0  19.0  28.0  18.0
1   3.0   8.0  12.0
2  16.0  15.0  11.0